#!/bin/bash
# custom squeue format

# custom format, with placeholders for future right-alignment
# | tabulation
# | right-alignment of numeric fields
command squeue -o '%Q; %T %i %u %j %M; %P %D; %C; %m; %E %R NL' "$@" \
  | column -t \
  | sed -E -e "s/([^ ]+);([ ]*)/\2\1 /g" -e "s/[ ]*NL$//g"
